server:
  port: 8080
  servlet:
    session:
      timeout: 30

spring:
  datasource:
    password: ToKreDi*nJ
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@10.192.19.163:1521/orcl
    username: ZHFTYJJCPT


security:
  basic:
    enabled: false

logging:
  level:
    root: INFO

mybatis:
  #指向mapper的xml文件位置
  mapper-locations: classpath:com.justplay1994.github.unifiedauth.dao.mapper/*Mapper.xml
  #指向实体类的位置
  type-aliases-package: classpath:com.justplay1994.github.unifiedauth.dao.entity.*
